#!/usr/bin/env python3
"""
Analyze recovery papers with detailed grep output for manual review.
"""

import json
import os
import subprocess
from pathlib import Path

def key_to_filename(key):
    """Convert paper key to filename"""
    return key.replace(':', '_').replace('/', '_')

def check_paper(key, fulltext_dir):
    """Check if paper text exists and is large enough"""
    filename = key_to_filename(key)
    text_path = os.path.join(fulltext_dir, f"{filename}.txt")

    if not os.path.exists(text_path):
        return None, "MISSING"

    size = os.path.getsize(text_path)
    if size < 3000:
        return None, f"TOO_SMALL ({size} bytes)"

    return text_path, "OK"

def get_grep_results(text_path):
    """Get grep results for all patterns"""
    patterns = [
        'teacher',
        'distill',
        'generated by',
        'data source',
        'source model',
        'ablat',
        'trajectories from',
        'GPT',
        'Claude',
        'Gemini',
        'DeepSeek',
        'Qwen',
        'GLM',
        'Kimi',
        'Llama',
        'MiniMax',
        r'o[134]',
    ]

    results = {}
    for pattern in patterns:
        try:
            result = subprocess.run(
                ['grep', '-n', '-i', '-A2', '-B2', pattern, text_path],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.stdout:
                lines = result.stdout.strip().split('\n')
                results[pattern] = lines[:5]  # First 5 occurrences
        except Exception:
            pass

    return results

def main():
    litmine_dir = "/data/cat/ws/frwe188h-otagent/OpenThoughts-Agent-trp/data/teacher_ranking_proxy/litmine"
    fulltext_dir = os.path.join(litmine_dir, "work", "state", "fulltext")
    recovery_dir = os.path.join(litmine_dir, "work", "state", "recovery_agents")

    assignment_file = os.path.join(recovery_dir, "rec_005.json")

    with open(assignment_file, 'r') as f:
        keys = json.load(f)

    print(f"Checking {len(keys)} papers...\n")

    for i, key in enumerate(keys, 1):
        text_path, status = check_paper(key, fulltext_dir)

        print(f"[{i:2d}/{len(keys)}] {key:20s} -> {status}")

        if text_path:
            results = get_grep_results(text_path)
            if results:
                print(f"       Found patterns: {', '.join(results.keys())}")
                # Show some highlights
                for pattern in ['ablat', 'teacher', 'generated by', 'trajectories from']:
                    if pattern in results:
                        print(f"       {pattern}: {results[pattern][0][:80]}")
            else:
                print(f"       No pattern hits found")
        print()

if __name__ == "__main__":
    main()
