#!/usr/bin/env python3
"""
More careful recovery analysis targeting the specific pattern:
- SAME pre-SFT student model
- SFT SEPARATELY on trajectories from EACH of >=2 teacher models
- On same or closely controlled tasks
- With per-teacher downstream scores
"""
import json
import subprocess
import os
import sys
from pathlib import Path

def key_to_filename(key):
    """Convert arxiv:2502.13092 -> arxiv_2502.13092.txt"""
    filename = key.replace(":", "_").replace("/", "_") + ".txt"
    return filename

def check_file_exists(filepath):
    """Check if file exists and is large enough (>3000 chars)"""
    if not os.path.exists(filepath):
        return False, "fail_retrieval", "file not found"
    size = os.path.getsize(filepath)
    if size < 3000:
        return False, "fail_retrieval", f"file too small ({size} bytes)"
    return True, None, None

def grep_section(filepath, pattern, context_lines=3):
    """Get grep results with context"""
    try:
        result = subprocess.run(
            ["grep", "-n", "-i", f"-A{context_lines}", f"-B{context_lines}", pattern, filepath],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            return result.stdout.strip().split('\n')
    except:
        pass
    return []

def read_text_section(filepath, start_line, end_line):
    """Read a specific section of the file"""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()
            return ''.join(lines[max(0, start_line-1):min(len(lines), end_line)])
    except:
        return ""

def process_paper_careful(key, fulltext_dir):
    """Process paper with manual verification steps"""
    filename = key_to_filename(key)
    filepath = os.path.join(fulltext_dir, filename)

    exists, verdict, note = check_file_exists(filepath)
    if not exists:
        return {
            "key": key,
            "verdict": verdict,
            "evidence": note
        }

    # Read full text
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            text = f.read()
    except:
        return {"key": key, "verdict": "fail_retrieval", "evidence": "read error"}

    # SCAN: Look for key terms that might indicate multi-teacher ablation
    teacher_pattern = r"(?:generated by|from|trajectories from|data from|trained on)\s+(?:GPT|Claude|Gemini|DeepSeek|Qwen|Llama|LLaMA)"
    separate_sft_pattern = r"(?:separate|independently|each|per.*teacher).*(?:fine.?tun|sft|train)"
    table_pattern = r"table\s+\d+|figure\s+\d+"

    # Quick scan for critical signals
    has_teacher_generation = len(grep_section(filepath, "generated by", 2)) > 0 or \
                             len(grep_section(filepath, "trajectories from", 2)) > 0
    has_separate_sft = len(grep_section(filepath, "separate.*train", 2)) > 0 or \
                       len(grep_section(filepath, "ablat", 2)) > 0
    has_table_results = len(grep_section(filepath, "table", 2)) > 0

    # Check for key signals in combination
    multiple_teachers = text.count("GPT") + text.count("Claude") + text.count("DeepSeek") + \
                       text.count("Qwen") + text.count("Gemini") + text.count("Llama")

    # Strategy: Look for the specific "train student on teacher trajectories" pattern
    sft_hits = grep_section(filepath, "sft\\|supervised fine", 4)
    teacher_hits = grep_section(filepath, "teacher", 3)
    ablation_hits = grep_section(filepath, "ablation", 3)

    # Heuristic checks for the target pattern
    signal_score = 0

    # Check if mentions multiple teachers AND SFT
    if multiple_teachers >= 3 and sft_hits:
        signal_score += 1

    # Check for "trajectories from X" pattern
    for teacher in ["GPT", "Claude", "DeepSeek", "Qwen"]:
        if f"from {teacher}" in text or f"trajectories from {teacher}" in text.lower():
            signal_score += 2

    # Check for ablation that compares different teachers
    if "ablation" in text.lower():
        if any(t in text for t in ["GPT", "Claude", "DeepSeek"]):
            if text.lower().count("sft") >= 2 or text.lower().count("training") >= 3:
                signal_score += 1

    # If low signal, return fail_scan
    if signal_score == 0:
        strongest = sft_hits[0] if sft_hits else teacher_hits[0] if teacher_hits else "no clear signal"
        return {
            "key": key,
            "verdict": "fail_scan",
            "evidence": f"no multi-teacher SFT signal; {strongest[:100]}" if len(str(strongest)) > 10 else "no clear pattern"
        }

    # Moderate to strong signal - need manual review for pass vs fail_ablation
    # For now, mark for review
    evidence_lines = []
    if sft_hits:
        evidence_lines.append(f"SFT: {sft_hits[0][:120]}")
    if ablation_hits:
        evidence_lines.append(f"Ablation: {ablation_hits[0][:120]}")

    # Check if it mentions same student model
    same_student_mentions = []
    for line in text.split('\n'):
        if 'same' in line.lower() and ('model' in line.lower() or 'student' in line.lower()):
            same_student_mentions.append(line[:120])

    if same_student_mentions:
        evidence_lines.append(f"Same model: {same_student_mentions[0]}")

    return {
        "key": key,
        "verdict": "pass",  # PROVISIONAL - requires human verification
        "evidence": "; ".join(evidence_lines) if evidence_lines else "plausible multi-teacher signal"
    }

def main():
    assignment_file = "work/state/recovery_agents/rec_008.json"
    output_file = "work/state/recovery_agents/recout_008.jsonl"
    fulltext_dir = "work/state/fulltext"

    with open(assignment_file, 'r') as f:
        papers = json.load(f)

    results = []
    pass_count = 0
    fail_count = 0

    for key in papers:
        result = process_paper_careful(key, fulltext_dir)
        results.append(result)

        if result["verdict"] == "pass":
            pass_count += 1
            print(f"PASS (requires review): {key}")
        else:
            fail_count += 1
            print(f"{result['verdict']}: {key}")

    # Write output
    with open(output_file, 'w') as f:
        for result in results:
            f.write(json.dumps(result) + '\n')

    print(f"\nResults: {len(results)} papers processed")
    print(f"Pass (provisional): {pass_count}, Fail: {fail_count}")

if __name__ == "__main__":
    main()
