#!/usr/bin/env python3
import json
import os
import re
import sys

# Papers to process
papers = [
    "arxiv:2603.04868",
    "arxiv:2603.05044",
    "arxiv:2603.05120",
    "arxiv:2603.05553",
    "arxiv:2603.05578",
    "arxiv:2603.05860",
    "arxiv:2603.05980",
    "arxiv:2603.06713",
    "arxiv:2603.06902",
    "arxiv:2603.07528",
    "arxiv:2603.07915",
    "arxiv:2603.07927",
    "arxiv:2603.08068",
    "arxiv:2603.08127",
    "arxiv:2603.08719",
]

def convert_key_to_filename(key):
    """Convert arxiv:2603.04868 to arxiv_2603.04868.txt"""
    return key.replace(':', '_').replace('/', '_') + '.txt'

def process_paper(key):
    """Main processing logic for a single paper"""
    
    text_filename = convert_key_to_filename(key)
    text_path = f"work/state/fulltext/{text_filename}"
    
    # Check if file exists and has minimum size
    if not os.path.exists(text_path):
        return {
            "key": key,
            "verdict": "fail_retrieval",
            "evidence": "Text file missing"
        }
    
    try:
        with open(text_path, 'r', encoding='utf-8', errors='ignore') as f:
            text = f.read()
    except Exception as e:
        return {
            "key": key,
            "verdict": "fail_retrieval",
            "evidence": f"Could not read file: {e}"
        }
    
    if len(text) < 3000:
        return {
            "key": key,
            "verdict": "fail_retrieval",
            "evidence": f"Text too short ({len(text)} chars)"
        }
    
    # Patterns to search for
    patterns = [
        'teacher',
        'distill',
        'generated by',
        'data source',
        'source model',
        'ablat',
        'trajectories from',
        'GPT',
        'Claude',
        'Gemini',
        'DeepSeek',
        'Qwen',
        'GLM',
        'Kimi',
        'Llama',
        'MiniMax',
        'o1',
        'o3',
        'o4',
    ]
    
    hits = {}
    for pattern in patterns:
        regex = re.compile(pattern, re.IGNORECASE)
        matches = []
        for i, line in enumerate(text.split('\n'), 1):
            if regex.search(line):
                matches.append((i, line.strip()[:150]))
        if matches:
            hits[pattern] = matches[:3]
    
    # If no hits on key patterns
    if not hits or not any(p in hits for p in ['teacher', 'distill', 'generated by', 'source model', 'ablat', 'trajectories from']):
        return {
            "key": key,
            "verdict": "fail_scan",
            "evidence": "No hits on key patterns (teacher, distill, generated by, source model, ablat, trajectories from)"
        }
    
    # Look for frontier model mentions
    frontier_models = ['GPT', 'Claude', 'Gemini', 'DeepSeek', 'Qwen', 'GLM', 'Llama']
    model_mentions = {}
    for model in frontier_models:
        if model in hits:
            model_mentions[model] = len(hits[model])
    
    # Get best evidence
    best_hit = None
    if 'teacher' in hits and hits['teacher']:
        best_hit = ('teacher', hits['teacher'][0])
    elif 'distill' in hits and hits['distill']:
        best_hit = ('distill', hits['distill'][0])
    elif 'generated by' in hits and hits['generated by']:
        best_hit = ('generated by', hits['generated by'][0])
    elif 'source model' in hits and hits['source model']:
        best_hit = ('source model', hits['source model'][0])
    elif 'ablat' in hits and hits['ablat']:
        best_hit = ('ablat', hits['ablat'][0])
    
    if best_hit:
        evidence_note = f"{best_hit[0]}: {best_hit[1][1]}"
    else:
        evidence_note = "Keyword hits but unclear signal"
    
    # Verdict: fail_scan for now - will need manual review with full context
    return {
        "key": key,
        "verdict": "fail_scan",
        "evidence": evidence_note
    }

# Main execution
results = []
for key in papers:
    result = process_paper(key)
    results.append(result)
    print(f"Processed {key}: {result['verdict']}")

# Write output
output_path = "work/state/recovery_agents/recout_045.jsonl"
with open(output_path, 'w') as f:
    for result in results:
        f.write(json.dumps(result) + '\n')

print(f"\nWrote {len(results)} results to {output_path}")
