#!/usr/bin/env python3
"""
Recovery scan for multi-teacher SFT ablations.
Process papers according to RECOVERY.md procedure.
"""

import json
import os
import re
import subprocess

def key_to_filename(key):
    """Convert paper key to filename: arxiv:2410.16024 -> arxiv_2410.16024"""
    return key.replace(':', '_').replace('/', '_')

def read_fulltext(text_path):
    """Read fulltext file, return (content, success).
    If missing or too small, return (None, False)"""
    if not os.path.exists(text_path):
        return None, False

    try:
        with open(text_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
    except Exception:
        return None, False

    if len(content) < 3000:
        return None, False

    return content, True

def grep_patterns(text_path):
    """Use grep to find pattern hits with context.
    Returns list of hits as strings"""

    patterns = [
        'teacher',
        'distill',
        'generated by',
        'data source',
        'source model',
        'ablat',
        'trajectories from',
        'GPT',
        'Claude',
        'Gemini',
        'DeepSeek',
        'Qwen',
        'GLM',
        'Kimi',
        'Llama',
        'MiniMax',
        r'o[134]',
    ]

    all_hits = []
    for pattern in patterns:
        try:
            # Use grep -n -i -A2 -B2
            result = subprocess.run(
                ['grep', '-n', '-i', '-A2', '-B2', pattern, text_path],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.stdout:
                all_hits.append((pattern, result.stdout))
        except Exception:
            pass

    return all_hits

def process_paper(key, fulltext_dir):
    """Process one paper, return (verdict, evidence)"""

    filename = key_to_filename(key)
    text_path = os.path.join(fulltext_dir, f"{filename}.txt")

    # Try to read fulltext
    content, success = read_fulltext(text_path)
    if not success:
        return "fail_retrieval", ""

    # Grep for patterns
    all_hits = grep_patterns(text_path)

    if not all_hits:
        return "fail_scan", "No relevant patterns found"

    # Find strongest hits - look for ablation or multi-teacher signals
    strongest_lines = []
    for pattern, grep_output in all_hits:
        lines = grep_output.strip().split('\n')
        for line in lines:
            if any(word in line.lower() for word in ['ablat', 'teacher', 'student', 'model', 'sft']):
                strongest_lines.append(line)

    # Return first 200 chars of strongest evidence
    if strongest_lines:
        evidence = strongest_lines[0][:150]
    else:
        evidence = f"Found {len(all_hits)} pattern hits but no clear ablation signal"

    return "fail_scan", evidence

def main():
    # Work directory
    litmine_dir = "/data/cat/ws/frwe188h-otagent/OpenThoughts-Agent-trp/data/teacher_ranking_proxy/litmine"
    fulltext_dir = os.path.join(litmine_dir, "work", "state", "fulltext")
    recovery_dir = os.path.join(litmine_dir, "work", "state", "recovery_agents")

    assignment_file = os.path.join(recovery_dir, "rec_005.json")
    output_file = os.path.join(recovery_dir, "recout_005.jsonl")

    # Read assignment
    with open(assignment_file, 'r') as f:
        keys = json.load(f)

    print(f"Processing {len(keys)} papers...")
    output_lines = []

    for i, key in enumerate(keys, 1):
        print(f"  [{i}/{len(keys)}] {key}")
        verdict, evidence = process_paper(key, fulltext_dir)
        result = {
            "key": key,
            "verdict": verdict,
            "evidence": evidence
        }
        output_lines.append(json.dumps(result))

    # Write output
    with open(output_file, 'w') as f:
        for line in output_lines:
            f.write(line + '\n')

    print(f"\nWrote {len(output_lines)} lines to {output_file}")

    # Verify
    result = os.popen(f"wc -l {output_file}").read().strip()
    print(f"Verification: {result}")

if __name__ == "__main__":
    main()
