"""Candidate discovery across arXiv, OpenAlex, Semantic Scholar (optional,
rate-limited without a key), Hugging Face and GitHub, plus citation/reference
expansion from seed papers via OpenAlex (and S2 when available).

Every source query is cached; discovery is deterministic given cached results.
Candidates are keyed by arXiv id when one is known, else by URL.
"""
from __future__ import annotations

import itertools
import logging
import os
import re
import urllib.parse
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from typing import Iterable

from .cache import Cache, cache_key
from .retrieval import Fetcher, norm_arxiv_id

log = logging.getLogger("litmine.discovery")

# Concept groups (PIPELINE.md §4.1). Queries are built from cross-products of
# one term per group so discovery never hinges on a single keyword phrase.
TEACHER_TERMS = ["teacher trajectories", "multiple teachers", "teacher model ablation",
                 "teacher selection", "teacher-generated data", "trajectory distillation",
                 "knowledge distillation"]
TRAINING_TERMS = ["SFT", "supervised fine-tuning", "trajectory dataset"]
AGENT_TERMS = ["agent", "agentic", "terminal", "SWE", "software engineering agent",
               "tool use", "interactive environment"]

DEFAULT_HF_QUERIES = ["teacher trajectories", "agent trajectories sft", "terminal agent",
                      "swe agent trajectories", "tool use trajectories", "trajectory distillation",
                      "agent traces", "swe-bench trajectories", "terminal-bench trajectories",
                      "gui agent trajectories", "web agent trajectories", "agentic sft data",
                      "distilled trajectories", "agent distillation"]
DEFAULT_GITHUB_QUERIES = ["teacher trajectories SFT agent", "agent trajectory distillation",
                          "terminal agent SFT trajectories"]


@dataclass
class Candidate:
    key: str                      # arxiv:<id> | url:<url>
    arxiv_id: str | None
    url: str | None
    title: str = ""
    abstract: str = ""
    year: int | None = None
    sources: list[str] = field(default_factory=list)   # provenance of discovery
    tags: list[str] = field(default_factory=list)
    hops: int = 0

    def merge(self, other: "Candidate") -> None:
        self.title = self.title or other.title
        self.abstract = self.abstract or other.abstract
        self.year = self.year or other.year
        self.url = self.url or other.url
        for s in other.sources:
            if s not in self.sources:
                self.sources.append(s)
        for t in other.tags:
            if t not in self.tags:
                self.tags.append(t)
        self.hops = min(self.hops, other.hops)

    def to_dict(self) -> dict:
        return {"key": self.key, "arxiv_id": self.arxiv_id, "url": self.url,
                "title": self.title, "abstract": self.abstract, "year": self.year,
                "sources": self.sources, "tags": self.tags, "hops": self.hops}


def build_arxiv_queries(max_queries: int | None = None) -> list[str]:
    qs = []
    for t, tr, a in itertools.product(TEACHER_TERMS, TRAINING_TERMS, AGENT_TERMS):
        qs.append(f'all:"{t}" AND all:"{tr}" AND all:"{a}"')
    # a few broader phrasings without the training group
    for t, a in itertools.product(["teacher trajectories", "trajectory distillation",
                                   "teacher-generated data"], ["agent", "terminal", "SWE"]):
        qs.append(f'all:"{t}" AND all:"{a}"')
    return qs[:max_queries] if max_queries else qs


def build_free_text_queries() -> list[str]:
    """Natural-language queries for OpenAlex / S2 (no boolean syntax)."""
    return [
        "teacher trajectories supervised fine-tuning agent",
        "multiple teachers trajectory distillation agent SFT",
        "teacher model ablation agentic supervised fine-tuning",
        "teacher selection trajectory data software engineering agent",
        "terminal agent SFT teacher-generated trajectories",
        "tool use agent knowledge distillation trajectories teachers",
        "interactive environment trajectories distillation student model teachers",
        "what makes trajectories effective for training agents",
        "SWE agent trajectory dataset teacher models fine-tuning comparison",
        "comparing teacher models for agent distillation downstream performance",
        "which teacher model generates the best training trajectories for agents",
        "student model fine-tuned on trajectories from different teacher LLMs",
        "agentic supervised fine-tuning data source ablation teacher",
        "GUI agent trajectories distilled from multiple teacher models",
        "web agent trajectory synthesis teacher model comparison fine-tuning",
        "tool-calling agent SFT data generated by different LLMs comparison",
        "terminal-bench SFT trajectories teacher",
        "SWE-bench agent SFT trajectories generated by Claude GPT comparison",
    ]


class Discovery:
    def __init__(self, fetcher: Fetcher, cache: Cache, per_query: int = 25):
        self.f = fetcher
        self.cache = cache
        self.per_query = per_query
        self.candidates: dict[str, Candidate] = {}
        self.stats: dict[str, int] = {}

    # ---- helpers ------------------------------------------------------------
    def _add(self, c: Candidate) -> None:
        if c.key in self.candidates:
            self.candidates[c.key].merge(c)
        else:
            self.candidates[c.key] = c
        self.stats[c.sources[0].split(":")[0]] = self.stats.get(c.sources[0].split(":")[0], 0) + 1

    def _cached(self, stage: str, **parts):
        key = cache_key(**parts)
        hit = self.cache.get(stage, key)
        return key, hit

    # ---- arXiv -----------------------------------------------------------------
    def arxiv_search(self, query: str, max_results: int | None = None) -> list[Candidate]:
        n = max_results or self.per_query
        key, hit = self._cached("search_arxiv", query=query, n=n)
        if hit is None:
            url = ("https://export.arxiv.org/api/query?" + urllib.parse.urlencode(
                {"search_query": query, "max_results": n, "sortBy": "relevance"}))
            status, body, _ = self.f.get(url)
            entries = []
            if status == 200:
                ns = {"a": "http://www.w3.org/2005/Atom"}
                for e in ET.fromstring(body).findall("a:entry", ns):
                    aid = norm_arxiv_id(e.findtext("a:id", "", ns))
                    if not aid:
                        continue
                    pub = e.findtext("a:published", "", ns) or ""
                    entries.append({"arxiv_id": aid,
                                    "title": " ".join((e.findtext("a:title", "", ns) or "").split()),
                                    "abstract": " ".join((e.findtext("a:summary", "", ns) or "").split()),
                                    "year": int(pub[:4]) if pub[:4].isdigit() else None})
            hit = self.cache.put("search_arxiv", key, {"query": query, "status": status,
                                                       "entries": entries})
        out = []
        for e in hit["entries"]:
            c = Candidate(key=f"arxiv:{e['arxiv_id']}", arxiv_id=e["arxiv_id"],
                          url=f"https://arxiv.org/abs/{e['arxiv_id']}", title=e["title"],
                          abstract=e["abstract"], year=e["year"], sources=[f"arxiv:{query}"])
            self._add(c)
            out.append(c)
        return out

    # ---- OpenAlex ------------------------------------------------------------
    def _openalex_work_to_candidate(self, w: dict, source: str, hops: int = 0) -> Candidate | None:
        arxiv = None
        for loc in (w.get("locations") or []) + [w.get("primary_location") or {}]:
            for u in (loc.get("landing_page_url"), loc.get("pdf_url")):
                if u and "arxiv.org" in u:
                    arxiv = norm_arxiv_id(u)
                    break
            if arxiv:
                break
        ids = w.get("ids") or {}
        url = ids.get("doi") or (w.get("primary_location") or {}).get("landing_page_url") or w.get("id")
        abstract = ""
        inv = w.get("abstract_inverted_index")
        if inv:
            pos = sorted((p, t) for t, ps in inv.items() for p in ps)
            abstract = " ".join(t for _, t in pos)
        if not arxiv and not url:
            return None
        key = f"arxiv:{arxiv}" if arxiv else f"url:{url}"
        return Candidate(key=key, arxiv_id=arxiv, url=f"https://arxiv.org/abs/{arxiv}" if arxiv else url,
                         title=w.get("title") or w.get("display_name") or "", abstract=abstract,
                         year=w.get("publication_year"), sources=[source],
                         tags=[f"openalex:{w.get('id')}"], hops=hops)

    def openalex_search(self, query: str, max_results: int | None = None) -> list[Candidate]:
        n = max_results or self.per_query
        key, hit = self._cached("search_openalex", query=query, n=n)
        if hit is None:
            url = "https://api.openalex.org/works?" + urllib.parse.urlencode(
                {"search": query, "per-page": n,
                 "select": "id,title,display_name,publication_year,ids,primary_location,locations,abstract_inverted_index,referenced_works,cited_by_api_url",
                 "mailto": os.environ.get("OPENALEX_MAILTO", "litmine@example.org")})
            try:
                data = self.f.get_json(url)
                hit = {"query": query, "results": data.get("results", [])}
            except Exception as e:
                log.warning("openalex search failed for %r: %s", query, e)
                hit = {"query": query, "results": [], "error": str(e)}
            self.cache.put("search_openalex", key, hit)
        out = []
        for w in hit["results"]:
            c = self._openalex_work_to_candidate(w, f"openalex:{query}")
            if c:
                self._add(c)
                out.append(c)
        return out

    def openalex_lookup(self, arxiv_id: str | None = None, title: str | None = None) -> dict | None:
        """Find the OpenAlex work for a paper (by arXiv id via locations, else title)."""
        key, hit = self._cached("openalex_lookup", arxiv_id=arxiv_id, title=title)
        if hit is not None:
            return hit.get("work")
        work = None
        sel = "id,title,display_name,publication_year,ids,primary_location,locations,abstract_inverted_index,referenced_works,cited_by_api_url,cited_by_count"
        tries = []
        if arxiv_id:
            tries.append("https://api.openalex.org/works?" + urllib.parse.urlencode(
                {"filter": f"locations.landing_page_url:https://arxiv.org/abs/{arxiv_id}",
                 "select": sel, "per-page": 5}))
        if title:
            tries.append("https://api.openalex.org/works?" + urllib.parse.urlencode(
                {"search": title, "select": sel, "per-page": 5}))
        for url in tries:
            try:
                res = self.f.get_json(url).get("results", [])
            except Exception as e:
                log.warning("openalex lookup failed: %s", e)
                continue
            for w in res:
                c = self._openalex_work_to_candidate(w, "lookup")
                if arxiv_id and c and c.arxiv_id == arxiv_id:
                    work = w
                    break
                if title and c and _norm_title(c.title) == _norm_title(title):
                    work = w
                    break
            if work:
                break
        self.cache.put("openalex_lookup", key, {"work": work})
        return work

    def openalex_expand(self, work: dict, hops: int, max_results: int = 200) -> list[Candidate]:
        """References + citations of an OpenAlex work."""
        out: list[Candidate] = []
        wid = work.get("id")
        # citations
        key, hit = self._cached("openalex_cites", wid=wid, n=max_results)
        if hit is None:
            url = "https://api.openalex.org/works?" + urllib.parse.urlencode(
                {"filter": f"cites:{wid.rsplit('/', 1)[-1]}", "per-page": min(max_results, 200),
                 "select": "id,title,display_name,publication_year,ids,primary_location,locations,abstract_inverted_index"})
            try:
                hit = {"results": self.f.get_json(url).get("results", [])}
            except Exception as e:
                hit = {"results": [], "error": str(e)}
            self.cache.put("openalex_cites", key, hit)
        for w in hit["results"]:
            c = self._openalex_work_to_candidate(w, f"cites:{wid}", hops)
            if c:
                self._add(c)
                out.append(c)
        # references (batched by id filter)
        refs = work.get("referenced_works") or []
        for i in range(0, len(refs), 50):
            batch = refs[i:i + 50]
            key, hit = self._cached("openalex_refs", ids=batch)
            if hit is None:
                url = "https://api.openalex.org/works?" + urllib.parse.urlencode(
                    {"filter": "openalex:" + "|".join(r.rsplit("/", 1)[-1] for r in batch),
                     "per-page": 50,
                     "select": "id,title,display_name,publication_year,ids,primary_location,locations,abstract_inverted_index"})
                try:
                    hit = {"results": self.f.get_json(url).get("results", [])}
                except Exception as e:
                    hit = {"results": [], "error": str(e)}
                self.cache.put("openalex_refs", key, hit)
            for w in hit["results"]:
                c = self._openalex_work_to_candidate(w, f"referenced_by:{wid}", hops)
                if c:
                    self._add(c)
                    out.append(c)
        return out

    # ---- Semantic Scholar (optional) ------------------------------------------
    def s2_expand(self, arxiv_id: str, hops: int) -> list[Candidate]:
        """Citations + references via Semantic Scholar. Skipped gracefully on 429
        (unauthenticated quota); set S2_API_KEY to enable reliably."""
        out: list[Candidate] = []
        hdr = {}
        if os.environ.get("S2_API_KEY"):
            hdr["x-api-key"] = os.environ["S2_API_KEY"]
        for kind in ("citations", "references"):
            key, hit = self._cached("s2_graph", arxiv_id=arxiv_id, kind=kind)
            if hit is None:
                url = (f"https://api.semanticscholar.org/graph/v1/paper/arXiv:{arxiv_id}/{kind}"
                       "?fields=title,abstract,year,externalIds,url&limit=500")
                try:
                    status, body, _ = self.f.get(url, headers=hdr)
                    import json
                    hit = {"status": status, "data": json.loads(body).get("data", []) if status == 200 else []}
                except Exception as e:
                    hit = {"status": 0, "data": [], "error": str(e)}
                if hit["status"] == 200:
                    self.cache.put("s2_graph", key, hit)
                else:
                    log.info("S2 %s for %s unavailable (status %s)", kind, arxiv_id, hit["status"])
            for row in hit["data"]:
                p = row.get("citingPaper") or row.get("citedPaper") or {}
                ext = p.get("externalIds") or {}
                aid = ext.get("ArXiv")
                url = f"https://arxiv.org/abs/{aid}" if aid else p.get("url")
                if not url:
                    continue
                c = Candidate(key=f"arxiv:{aid}" if aid else f"url:{url}", arxiv_id=aid, url=url,
                              title=p.get("title") or "", abstract=p.get("abstract") or "",
                              year=p.get("year"), sources=[f"s2_{kind}:{arxiv_id}"], hops=hops)
                self._add(c)
                out.append(c)
        return out

    # ---- Hugging Face ----------------------------------------------------------
    def hf_search(self, query: str, limit: int = 50) -> list[Candidate]:
        """Datasets whose card cites an arXiv paper become paper candidates; the
        dataset id is kept as a tag so artifact verification can use it."""
        key, hit = self._cached("search_hf", query=query, limit=limit)
        if hit is None:
            url = "https://huggingface.co/api/datasets?" + urllib.parse.urlencode(
                {"search": query, "limit": limit, "full": "true"})
            try:
                hit = {"results": self.f.get_json(url)}
            except Exception as e:
                hit = {"results": [], "error": str(e)}
            self.cache.put("search_hf", key, hit)
        out = []
        for d in hit["results"]:
            tags = d.get("tags") or []
            arxivs = [t.split(":", 1)[1] for t in tags if t.startswith("arxiv:")]
            for aid in arxivs:
                aid = norm_arxiv_id(aid)
                if not aid:
                    continue
                c = Candidate(key=f"arxiv:{aid}", arxiv_id=aid, url=f"https://arxiv.org/abs/{aid}",
                              sources=[f"hf:{query}"], tags=[f"hf_dataset:{d.get('id')}"])
                self._add(c)
                out.append(c)
        return out

    # ---- GitHub ----------------------------------------------------------------
    def github_search(self, query: str, limit: int = 20) -> list[Candidate]:
        """Repos whose description/README mention an arXiv id -> paper candidate."""
        key, hit = self._cached("search_github", query=query, limit=limit)
        if hit is None:
            hdr = {"Accept": "application/vnd.github+json"}
            if os.environ.get("GITHUB_TOKEN"):
                hdr["Authorization"] = f"Bearer {os.environ['GITHUB_TOKEN']}"
            url = "https://api.github.com/search/repositories?" + urllib.parse.urlencode(
                {"q": query, "per_page": limit})
            try:
                hit = {"items": self.f.get_json(url, headers=hdr).get("items", [])}
            except Exception as e:
                hit = {"items": [], "error": str(e)}
            self.cache.put("search_github", key, hit)
        out = []
        for it in hit["items"]:
            text = f"{it.get('description') or ''} {it.get('homepage') or ''}"
            aid = norm_arxiv_id(text) if "arxiv" in text.lower() else None
            if aid:
                c = Candidate(key=f"arxiv:{aid}", arxiv_id=aid, url=f"https://arxiv.org/abs/{aid}",
                              sources=[f"github:{query}"], tags=[f"github_repo:{it.get('full_name')}"])
            else:
                continue
            self._add(c)
            out.append(c)
        return out

    # ---- seeds & expansion -------------------------------------------------
    def add_seed(self, seed: str) -> Candidate:
        aid = norm_arxiv_id(seed)
        if aid:
            c = Candidate(key=f"arxiv:{aid}", arxiv_id=aid, url=f"https://arxiv.org/abs/{aid}",
                          sources=["seed"])
        else:
            c = Candidate(key=f"url:{seed}", arxiv_id=None, url=seed, sources=["seed"])
        self._add(c)
        return c

    def expand_citations(self, seeds: Iterable[Candidate], depth: int = 1) -> None:
        frontier = list(seeds)
        seen: set[str] = set()
        for hop in range(1, depth + 1):
            nxt: list[Candidate] = []
            for c in frontier:
                if c.key in seen:
                    continue
                seen.add(c.key)
                work = self.openalex_lookup(arxiv_id=c.arxiv_id, title=c.title or None)
                if work:
                    nxt += self.openalex_expand(work, hops=hop)
                if c.arxiv_id:
                    nxt += self.s2_expand(c.arxiv_id, hops=hop)
            frontier = nxt

    def run(self, seeds: list[str], *, arxiv_queries: list[str] | None = None,
            free_queries: list[str] | None = None, hf_queries: list[str] | None = None,
            github_queries: list[str] | None = None, citation_depth: int = 1,
            use_github: bool = True) -> list[Candidate]:
        seed_cands = [self.add_seed(s) for s in seeds]
        for q in (arxiv_queries if arxiv_queries is not None else build_arxiv_queries()):
            self.arxiv_search(q)
        for q in (free_queries if free_queries is not None else build_free_text_queries()):
            self.openalex_search(q)
        for q in (hf_queries if hf_queries is not None else DEFAULT_HF_QUERIES):
            self.hf_search(q)
        if use_github:
            for q in (github_queries if github_queries is not None else DEFAULT_GITHUB_QUERIES):
                self.github_search(q)
        if citation_depth > 0:
            self.expand_citations(seed_cands, depth=citation_depth)
        return sorted(self.candidates.values(), key=lambda c: (c.hops, c.key))


def _norm_title(t: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", (t or "").lower()).strip()
