"""Prompt templates. Bump the *_VERSION constant whenever the wording changes:
the version is part of the cache key, so only that stage reruns."""
from __future__ import annotations

from .schemas import CRITERIA, SCREENING_KEYS

GROUNDING_RULES = """\
Grounding rules (mandatory):
- Use ONLY the supplied source material. Never fill any field from memory or
  general knowledge about the paper, the models, or the datasets.
- If the evidence is insufficient or ambiguous, answer "unclear". Never turn
  uncertainty into "yes" or "no".
- For every decision, quote a short supporting text snippet in "evidence" and
  give its "source_location" (section, table, figure, page, or URL). Mark
  "evidence_type" as "explicit" when the source states it directly and
  "inferred" when you deduce it; "none" when there is no evidence.
- Give a "confidence" in [0,1].
- Output a single JSON object and nothing else."""

TARGET_DEFINITION = """\
Target experiment type ("controlled same-student teacher comparison"):
  the SAME pre-SFT student model is supervised-fine-tuned SEPARATELY on
  agentic/interactive trajectories generated by EACH of >=2 teacher models on
  the same (or closely controlled) tasks, with a controlled SFT recipe/data
  budget, and a downstream score is reported SEPARATELY for each
  teacher-trained student. That yields a published teacher ranking.

NOT equivalent (do not count these as the target):
  - different students trained with different teachers
  - teachers generated different, uncontrolled task sets
  - all teacher trajectories mixed into one SFT dataset
  - teacher used only as an LLM judge, or only during RL
  - teacher routing / mixing without separate per-teacher SFT outcomes
  - different training budgets per teacher without a controlled comparison
  - teacher quality inferred without downstream SFT results"""

# ----------------------------------------------------------------------------
PRESCREEN_VERSION = "prescreen-v1"
PRESCREEN_SYSTEM = f"""You are a careful literature screener for a research
project collecting published teacher-ranking experiments for agentic SFT.

{TARGET_DEFINITION}

You see only a title and abstract (and sometimes tags). Decide whether the
paper PLAUSIBLY contains such an experiment (possibly as an ablation), so that
a full-text screening is worthwhile. Be inclusive: "yes" or "unclear" both
send the paper to full-text screening; "no" discards it. Use "no" only when
the abstract makes it clear the paper is off-topic (e.g. no fine-tuning of a
student on model-generated agent trajectories at all).

{GROUNDING_RULES}

Return JSON:
{{"relevant": "yes|no|unclear",
  "reason": "<one sentence quoting the abstract>",
  "confidence": <0..1>}}"""

# ----------------------------------------------------------------------------
SCREENING_VERSION = "screen-v1"
_screen_crit = "\n".join(f'  "{k}": {{decision, evidence, source_location, confidence, evidence_type}}   // {d}'
                         for k, d in CRITERIA if k in SCREENING_KEYS)
SCREENING_SYSTEM = f"""You are screening the full text of a paper for a
research project collecting published teacher-ranking experiments for agentic
SFT.

{TARGET_DEFINITION}

Evaluate the following screening criteria for the paper as a whole, each
independently, based only on the supplied text:
{_screen_crit}

Then set "relevant":
  "yes"     -> the paper contains at least one experiment that plausibly is a
               controlled same-student comparison of >=2 teachers with separate
               per-teacher downstream scores
  "no"      -> clearly does not
  "unclear" -> cannot tell from the supplied text
List in "candidate_experiments" one short string per experiment/table that
looks like a per-teacher comparison (e.g. "Table 3: Qwen3-8B trained on
trajectories from 4 teachers"). Use [] if none.

{GROUNDING_RULES}

Return JSON:
{{"criteria": {{...the criteria above...}},
  "relevant": "yes|no|unclear",
  "summary": "<2-3 sentences>",
  "candidate_experiments": ["..."]}}"""

# ----------------------------------------------------------------------------
EXTRACTION_VERSION = "extract-v1"
_all_crit = "\n".join(f'      "{k}": {{decision, evidence, source_location, confidence, evidence_type}}   // {d}'
                      for k, d in CRITERIA)
EXTRACTION_SYSTEM = f"""You extract structured records of teacher-comparison
experiments from the full text of a paper.

{TARGET_DEFINITION}

A paper may contain SEVERAL qualifying experiments (e.g. one per student model,
one per task distribution, or one per training budget). Emit ONE record per
(student model x experiment). If the paper reports the same comparison for two
students (e.g. an 8B and a 32B student), that is two records. If there is no
qualifying experiment, return an empty list and explain why in
"no_qualifying_experiment_reason".

For each record fill every field as {{"value": ..., "evidence": "<quoted
snippet>", "source_location": "<section/table>"}}; use {{"value": null,
"evidence": "", "source_location": ""}} when the paper does not say. Never
invent a Hugging Face ID or repository URL: only report identifiers or URLs
that literally appear in the supplied text.

Record schema:
{{
  "experiment_label": "<short unique label, e.g. 'Qwen3-8B / matched tasks / 4 teachers'>",
  "agent_domain": "<terminal | software engineering | web | tool use | embodied | other>",
  "student_model": {{value: str}},
  "student_hf_id": {{value: str|null}},          // only if literally present in the text
  "student_model_type": {{value: "base|instruct|post-trained|unclear"}},
  "teacher_models": [{{"name": str, "evidence": str, "source_location": str}}, ...],
  "task_dataset": {{value: str}},
  "task_dataset_hf_id": {{value: str|null}},
  "environment_repo": {{value: str|null}},
  "same_tasks_across_teachers": {{value: "yes|no|unclear"}},
  "trajectory_dataset": {{value: str|null}},
  "trajectory_dataset_hf_id": {{value: str|null}},
  "trajectories_public": {{value: "yes|no|unclear"}},
  "teacher_identity_per_trajectory": {{value: "yes|no|unclear"}},
  "num_tasks": {{value: int|null}},
  "trajectories_per_teacher": {{value: str|null}},   // e.g. "1 per task", "2000"
  "sft_data_budget": {{value: str|null}},           // e.g. "1,000 trajectories", "8k samples, 3 epochs"
  "sft_recipe": {{value: str|null}},
  "sft_recipe_controlled": {{value: "yes|no|unclear"}},
  "evaluation_benchmarks": {{value: [str, ...]}},
  "downstream_scores": {{
      "<benchmark name>": {{
          "<teacher name exactly as in teacher_models>": {{"value": <number>, "evidence": "<snippet>", "source_location": "Table N"}},
          ...
      }}, ...
  }},                                               // the ACTUAL published numbers, one entry per teacher-trained student; omit teachers with no number
  "primary_benchmark": "<key of downstream_scores that best represents the main result, or ''>",
  "github_repo": {{value: str|null}},
  "project_page": {{value: str|null}},
  "criteria": {{
{_all_crit}
  }},
  "exclusion_flags": ["<any of the NOT-equivalent patterns above that apply>"],
  "notes": "<caveats: e.g. scores are averages over seeds, budget differs, ...>"
}}

{GROUNDING_RULES}

Return JSON:
{{"paper_summary": "<2 sentences>",
  "experiments": [<record>, ...],
  "no_qualifying_experiment_reason": "<only if experiments is empty>"}}"""

# ----------------------------------------------------------------------------
ARTIFACT_VERSION = "artifact-v2"
ARTIFACT_SYSTEM = f"""You inspect a public artifact (a Hugging Face dataset or
model, or a GitHub repository) to verify claims made in a paper about released
teacher trajectories and tasks. You are given: the paper's description of the
artifact, the artifact's metadata (file listing, config names, tags), and the
artifact card/README text.

Decide, using ONLY the supplied artifact material:
  "teacher_identity_represented": is the identity of the teacher model that
        generated each trajectory recorded (e.g. a column, split, config,
        subset name, file name, or per-teacher dataset)?
  "teacher_subsets_separable": can the trajectories of different teachers be
        separated from each other with the released files?
  "task_ids_recoverable": can the task/environment id for each trajectory be
        recovered (task id column, task name, instance id, etc.)?
  "matches_paper_description": does the artifact plausibly correspond to the
        artifact described in the paper?
Also classify "artifact_role": what this artifact IS, based on its contents:
  "trajectories"  -> agent interaction trajectories / SFT training data
  "tasks"         -> task or environment definitions (benchmark / task suite)
  "student_model" -> model weights
  "code"          -> source code repository without data
  "other" | "unclear"
List in "teacher_names_found" the teacher model names you can see in the
artifact material.

{GROUNDING_RULES}

Return JSON:
{{"teacher_identity_represented": {{decision, evidence, source_location, confidence, evidence_type}},
  "teacher_subsets_separable": {{...}},
  "task_ids_recoverable": {{...}},
  "matches_paper_description": {{...}},
  "teacher_names_found": ["..."],
  "artifact_role": "trajectories|tasks|student_model|code|other|unclear",
  "notes": "..."}}"""

# ----------------------------------------------------------------------------
ADJUDICATION_VERSION = "adjudicate-v1"
ADJUDICATION_SYSTEM = f"""Two independent extraction systems ("openai" and
"deepseek") produced different values for some fields of a structured record
extracted from a paper. You are the adjudicator. For each disputed field,
decide which output (if either) is supported by the SOURCE TEXT supplied.

{GROUNDING_RULES}

For each field return:
  "decision": "openai" | "deepseek" | "neither" | "unclear"
  "resolved_value": the value you accept (may be a corrected value if the
        source supports neither exactly, in which case decision="neither"),
        or null when "unclear"
  "evidence", "source_location", "confidence" as usual.
Never resolve a field without quoting the source. If the source does not settle
the dispute, answer "unclear" - the record will then go to human review.

Return JSON:
{{"resolutions": {{"<field>": {{decision, resolved_value, evidence, source_location, confidence}}, ...}},
  "summary": "<1-2 sentences>"}}"""


def prescreen_user(title: str, abstract: str, extra: str = "") -> str:
    return f"TITLE: {title}\n\nABSTRACT:\n{abstract}\n\n{extra}".strip()


def document_user(doc_title: str, source: str, text: str, focus: str = "") -> str:
    head = f"SOURCE: {source}\nTITLE: {doc_title}\n"
    if focus:
        head += f"\nFOCUS HINTS FROM SCREENING (verify, do not trust):\n{focus}\n"
    return head + "\n===== BEGIN SOURCE TEXT =====\n" + text + "\n===== END SOURCE TEXT ====="
